name: publish to npmjs when push tag
on:
  create:
    tags:
      - "utils-ts@[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:
  workflow_run:
    workflows: ["add tag when pr marged"]
    types: ["completed"]

env:
  GH_USER_EMAIL: 41898282+github-acitons[bot]@users.noreply.github.com
  GH_USER_NAME: github-acitons[bot]
  TAG_VERSION_PREFIX: v

jobs:
  publish-to-npmjs:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: get package version
        run: |
          version=`cat package.json | jq -r '.version'`
          pkg_name=`cat package.json | jq -r '.name | split("/") | .[1]'`
          new_tag="${pkg_name}@${version}"
          echo "NEW_VERSION=${version}"
          echo "NEW_TAG=${new_tag}"
          echo "NEW_VERSION=${version}" >> $GITHUB_ENV
          echo "NEW_TAG=${new_tag}" >> $GITHUB_ENV

      - name: check package version
        run: |
          # check package.version
          exists=`npm view "${{ env.NEW_TAG }}" version > /dev/null 2>&1 && echo $? || echo $?`
          if [ ! "$exists" -eq "0" ]; then
            echo "can publish version: ${{ env.NEW_TAG }}"
          else
            echo "::error ${{ env.NEW_TAG }} is already exists in npmjs"
            exit 1
          fi

      - name: install and build
        run: pnpm install && pnpm build

      - name: publish package
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: create release note
        run: gh release create ${{ env.NEW_TAG }} --generate-notes -d
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
